### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by 64801965** [wiiu-env/JsTypeHax_payload#1]
entry.c
utils.c
elf_loading.c
memory_setup.c
kernel_patches.S
linking ... main_hook.elf
make[2]: Leaving directory '/home/Terny/Downloads/JsTypeHax_payload/main_hook'
xxd -i main_hook/main_hook.elf | sed "s/unsigned/static const unsigned/g;s/loader/loader/g;s/build_//g" > main_hook.h
powerpc-eabi-gcc -std=gnu99 -Os -fno-builtin -DVER=550 -c ./launcher.c
./launcher.c: In function 'thread_callback':
./launcher.c:87:47: error: 'main_hook_main_hook_elf' undeclared (first use in this function)
     private_data.data_elf = (unsigned char *) main_hook_main_hook_elf; // use this address as temporary to load the elf
                                               ^~~~~~~~~~~~~~~~~~~~~~~
./launcher.c:87:47: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:32: main] Error 1
make[1]: Leaving directory '/home/Terny/Downloads/JsTypeHax_payload'
make: *** [Makefile:29: main550] Error 2

**Comment by cedkeChat** [comment]
"main_hook/main_hook.elf"

**Comment by cedkeChat** [comment]
you have to put in the launcher.c instead of main_hook_main_hook_elf you have to put "main_hook/main_hook.elf" (with quotes)

**Comment by Maschell** [comment]
Should now work again
